all:
	@./gen_dip.pl
	@./gen_TO220.pl
	@./gen_TO92.pl
	@./gen_resistor.pl
	@./gen_diode.pl
	@./gen_capacitor.pl
	@./gen_coil.pl
	@./gen_conn.pl
	@./gen_heatsink.pl
	@./gen_pot.pl
	@./gen_led.pl
	@./test.pl > test.fp

clean:
	rm -f *.fp *.fp-
